### ISSUE TITLE
Neither Paket nor its bootstrapper were found. It is suggested that you download the Paket boostrapper and save it as .paket/paket.exe

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-paket#80]
**Describe the bug**
I hadn't used VSCode+Paket in a while, and we have a couple of small projects at work that just consist of a bunch of fsx files. We used to be able to just run Paket: Init from VSCode when opening the folder for the first time on a new machine (I've put that on README.txt files all over since most people that use these scripts aren't familiar with F# or Paket at all), but now Ionide gives this error on the current version:

![image](https://user-images.githubusercontent.com/738761/66410311-d1526300-e9e9-11e9-9189-84656057aa61.png)

Has the functionality to auto download paket int he background and use it been removed?

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 4.1.0
 - VSCode version: 1.38.1
 - dotnet SDK version: 3.0.100
 - mono / .Net Framework version: 4.8

**Comment by Krzysztof-Cieslak** [comment]
Ionide-Paket hasn't been really touched at all in a while, I'll investigate.

**Comment by piaste** [comment]
I observed the same behaviour today. I have paket installed _only_ as a dotnet global tool, and since this  extension is over a year old I guess that's the most likely reason.

**Comment by 101v** [comment]
I am facing the same issue today. VSCode 1.41.1 and Ionide-Paket1.12.0

**Comment by Andegawen** [comment]
@piaste it looks like paket as dotnet global tool is not supported
https://github.com/ionide/ionide-vscode-paket/blob/master/src/paket.fs#L47
because the code looks at certain locations without trying to guess is paket installed as global.

@Krzysztof-Cieslak probably the easiest workaround would be adding a new entry to potential directories as 
* `%userprofile%/.dotnet/tools` for win
* `$HOME/.dotnet/tools` for Linux/macOS
[dotnet-tool-install](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)

so Ionide-Paket should start working :)

**Comment by KingKnecht** [comment]
> ...
> @Krzysztof-Cieslak probably the easiest workaround would be adding a new entry to potential directories ...

How do I do that? Where should I add it? Somewhere in the preferences? Or in a environment path variable? Or somewhere else?

Thx

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.0`
